plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.d4ocr'
version = '0.7.10'

android {
  namespace "expo.modules.d4ocr"
  defaultConfig {
    versionCode 1
    versionName "0.7.10"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation("com.google.mlkit:text-recognition:16.0.1")
  implementation("androidx.exifinterface:exifinterface:1.3.7")
}
